salt_version: "3006"
salt_master_ip: "192.168.1.10"  # Replace with your Salt master IP address
minion_bundle_path: "/path/to/minion_bundle.tar.gz"  # Replace with the actual path to the bundled minion package